### ISSUE TITLE
Connect Wallet

### ISSUE THREAD

**Issue by rsodre** [underware-gg/pistols#13]
Connect with Starknet Wallets

- [x] Add a generic Starknet wallet connector package to the client
- [x] Support Argent
- [x] Allow guests to browse and watch duels, without the need to connect a Wallet
- [ ] Display stark name and Profile Picture at the Gate (needs [#420](https://github.com/apibara/starknet-react/issues/420))

Wallet management of Duelist (burner) accounts

- [x] Test/adapt burner API to work with wallet accounts
- [x] Implement deterministic burner account creation similar to Ethereum wallets, ideally into dojo create-burner
- [x] Allow wallets to restore burner accounts anywhere

**Comment by ktarun1419** [comment]
i want to work on this issue

**Comment by rsodre** [comment]
> i want to work on this issue

Awesome! Do you have familiarity with Dojo and Starknet?

At this moment, I'm adding wager and fees to the game's contract, I think it's best to do this afterward, to make sure it's working with the game.

Also, a lot is happening regarding L2 and L3s right now, and it will impact how this will be implemented.
We're considering deploying on [Realms L3](https://dev.realms.world/), which no doubt is the best place for the game to reside, but will take a while to go live on mainnet.

Close to this issue is the usage of Arcade Accounts, which also depends on the target L2/L3.

**Comment by ktarun1419** [comment]
yes i am familiar with starknet and dojo , Please let me know when i can start on this issue

**Comment by rsodre** [comment]
@ktarun1419, I spent the weekend researching account abstraction and decided to do this myself.

I opened another issue #24 that would be a good place to start, and it also involves collaboration with Dojo ([dojo.js#165](https://github.com/dojoengine/dojo.js/issues/165))
